services:

  mongodb:
    image: mongo
    container_name: valhalla-dev-mongodb   
    ports:
      - 27017:27017
    restart: unless-stopped       
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      valhalla-dev:
        ipv4_address: ${IP_MONGODB}

  mongo-express:
    image: mongo-express
    container_name: valhalla-dev-mongo-express 
    ports:
      - 8080:8081
    restart: unless-stopped  
    networks:
      - valhalla-dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ADMIN_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ADMIN_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${IP_MONGODB}
      - ME_CONFIG_MONGODB_PORT=27017

      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_WEB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_WEB_PASSWORD}

    links:
      - mongodb

networks:
  valhalla-dev:
    external: true
    name: valhalla-dev
    ipam:
      driver: default
      config:
        - subnet: ${MASK_MONGODB}
